// Authentication Actions
export const FETCH_USER    = 'FETCH_USER';
export const AUTH_START    = 'AUTH_START';
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_SUCCESS  = 'AUTH_SUCCESS';
export const AUTH_FAIL     = 'AUTH_FAIL';
export const AUTH_LOGOUT   = 'AUTH_LOGOUT';
export const AUTH_RESET    = 'AUTH_RESET';
export const AUTH_UPDATE   = 'AUTH_UPDATE';
export const MODAL_LOGIN   = 'MODAL_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_OUT       = 'LOG_OUT';
export const MOBILE_AUTH   = 'MOBILE_AUTH';
export const EMAIL_VERIFICATION = 'EMAIL_VERIFICATION';
// Downloading Movies Actions
export const START_LOADING_MOVIE = 'START_LOADING_MOVIE';
export const SUCCESS_LOADING     = 'SUCCESS_LOADING';
export const ERROR_LOADING       = 'ERROR_LOADING';
export const SUCCESS_LOADING_CERTAIN = 'SUCCESS_LOADING_CERTAIN';
// Characters & Team Component
export const SUCCES_LOAD_PERSON       = 'SUCCES_LOAD_PERSON';
export const SUCCES_LOAD_PERSON_STAFF = 'SUCCES_LOAD_PERSON_STAFF';
// Video Component
export const SUCCES_LOAD_VIDEO = 'SUCCES_LOAD_VIDEO';
// PERSON TYPES FOR DIVIDE FUNCTIONALITY
export const PERSON_CHARACTERS = 'PERSON_CHARACTERS';
export const PERSON_STAFF      = 'PERSON_STAFF';

export const SUCCESS_LOAD_SOCIAL = 'SUCCESS_LOAD_SOCIAL'

export const SESSION_ID_HANDLER = 'SESSION_ID_HANDLER';
export const SUCCESS_LOAD_ID    = 'SUCCESS_LOAD_ID';

export const UPDATE_MOVIE_LIST  = 'UPDATE_MOVIE_LIST';
export const UPDATE_MOVIE_ERROR = 'UPDATE_MOVIE_ERROR';

export const START_ADD_ITEM = 'START_ADD_ITEM';
export const SUCCESS_ITEM_ADDED = 'SUCCESS_ITEM_ADDED';
export const ERROR_ITEM_ADDED = 'ERROR_ITEM_ADDED';

export const ON_SIDE_CHANGED = 'ON_SIDE_CHANGED';

export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_ERROR = 'FETCH_USER_INFO_ERROR';

export const CHANGE_USER_PHOTO_START = 'CHANGE_USER_PHOTO_START';
export const CHANGE_USER_PHOTO_SUCCESS = 'CHANGE_USER_PHOTO_SUCCESS'
export const CHANGE_USER_PHOTO_ERROR = 'CHANGE_USER_PHOTO_ERROR';

export const LOADING_PERSONAL_LIST_START = 'LOADING_PERSONAL_LIST_START';
export const LOADING_PERSONAL_LIST_SUCC  = 'LOADING_PERSONAL_LIST_SUCC';
export const LOADING_PERSONAL_LIST_ERROR = 'LOADING_PERSONAL_LIST_ERROR'

export const PERSONAL_LIST_UPDATE_START = 'PERSONAL_LIST_UPDATE_START';
export const PERSONAL_LIST_UPDATE = 'PERSONAL_LIST_UPDATE';
